#!/bin/bash
#SBATCH --job-name=submit_begin
#SBATCH --output=log_submit_begin_%j.out
#SBATCH --error=log_submit_begin_%j.err
#SBATCH --partition=plgrid-gpu-a100
#SBATCH --account=plgllmparamgr-gpu-a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-gpu=4
#SBATCH --time=0-00:01:00
#SBATCH --mem=16G

echo "Starting submit_begin on host $(hostname)"

source $HOME/venv/bin/activate
source $SCRATCH/bml-2/.env

srun python ./main.py --n_training_steps 100